### ISSUE TITLE
Fix "spread your cards" issue, players cannot scroll through or select cards

### ISSUE THREAD

**Issue by NancyCat97** [KevinBongart/cards_against_humanity#103]
If a player clicks "spread your cards", they cannot read any card except the top card.  They also cannot scroll through the cards or select one to play.

There was an older "spread your cards" variant where each of the player's ten cards was displayed individually and the player could select whichever card they wanted.  This worked very well.

**Comment by KevinBongart** [comment]
Hi @NancyCat97, thank you for the bug report.

Apologies for the long wait, I was taking a month-long sabbatical away from computers. Upon coming back, I also noticed the app was down due to a bug in the SSL certificate system in place (which was supposed to automatically renew it but didn't).

The app is back up and I am able to reproduce the layout issue. It looks like a CSS bug, though I haven't changed anything in the code in a little while, so it could come from a 3rd party library (which I routinely update).

If anybody's interested in fixing this, the CSS is partly computed in the backend while generating the HTML for the player's cards, and the other part in declared in the CSS file.

I'll look into it in the coming days and keep you posted.

**Comment by KevinBongart** [comment]
Hey @NancyCat97, it looks like the bug is fixed: I clicked "Spread your cards" and all 10 cards were displayed correctly.

I bet the issue was introduced in a front-end library update and fixed the same way. Thank you for reporting the issue, hope you're still enjoying the game :)

**Comment by NancyCat97** [comment]
@KevinBongart My friends and I are indeed enjoying the game.  We play weekly.  Thanks!
